language: python
python:
  - "3.7-dev"  # 3.7 development branch
install:
  - pip install -e .
# command to run tests
script:
  - flake8 .
  - pytest
notifications:
  slack:
    rooms:
      - cmi-uzh:o2jdwEmDHNt9P2yRGMVneVbD#test-travis-int
    on_success: change # default: always
    on_failure: always # default: always